### ISSUE TITLE
Split schemas into core and vault

### ISSUE THREAD

**Issue by tahpot** [verida/schemas#9]
Current situation:

- All schemas deployed to https://schemas.testnet.verida.io/
- All schemas stored in this repo (https://github.com/verida/schemas/)

Need to split into:

- Core schemas (Verida protocol schemas; base, credential, inbox)
- Vault schemas ()
- Application specific or common ? schemas
- Need to deploy to different hostnames
  - core.schemas.verida.io
  - vault.schemas.verida.io
  - common.schemas.verida.io

**Comment by nick-verida** [comment]
Core
* Things that are needed for apps to work on the Verida network
* Used by the core protocol library
* eg:
  * Profile
  * security/key/symmetric
  * core
  * outbox


Vault
* auth

Common
* Contact
* Location tracking

**Comment by tahpot** [comment]
This will be the naming convention for schemas:

- https://schemas.verida.io/contact/latest/schema.json -> https://schemas.verida.io/contact/v0.2.0/schema.json
- https://schemas.verida.io/contact/v0.1.0/schema.json
- https://schemas.verida.io/contact/v0.2.0/schema.json

This is based on the conversation in the core protocol: https://github.com/verida/verida-js/issues/18

**Comment by nick-verida** [comment]
Nick to create 3 schema repos:
* core
* vault
* common

Setup deployment to S3 for these.

**Comment by tahpot** [comment]
Chris to:

- [x] Migrate essential schemas into the appropriate repo
- [x] Update schema filenames to match the new naming convention
- [x] [Update schema versions](https://github.com/verida/schemas/issues/15)
- [ ] Update `verida-js` to use the new schema URLs
- [ ] Update `vault-mobile` to use the new schema URLs
- [ ] Update all demos to use the new schema URLs

**Comment by tahpot** [comment]
@nick-verida I will configure `latest` to be a symlink to the latest version and so we can test if that deploy process will work without breaking things.

**Comment by nick-verida** [comment]
@tahpot  When you move them across, is it worth changing the JSON schema draft we reference at the same time? I don't know if that breaks anything, but it's something we have to do at some point?

**Comment by tahpot** [comment]
@nick-verida Yes, that's my plan.

**Comment by nick-verida** [comment]
@tahpot repos are ready. Currently set to private:

https://github.com/verida/schemas-core
https://github.com/verida/schemas-common
https://github.com/verida/schemas-vault

**Comment by tahpot** [comment]
@nick-verida I've pushed `base` schema to `schemas-core` with the `latest` symlink so you can test if that deploys correctly.

**Comment by tahpot** [comment]
I've hit my first issue.

When we link schemas we have to specify the URL of the schema (as per the JSON schema standard).

For example in the `inbox/entry` schema we have:

```
"allOf": [
        {"$ref": "/base/schema.json"},
        {
            "properties": {...}
        }
]
```

Should we reference the latest schema or a versioned schema for the base?

- `/base/schema/latest/schema.json`
- `/base/schema/v0.1.0/schema.json`

If we update a schema to have a non-breaking enhancement then linking to:

- `latest` will automatically include that non-breaking enhancement to all the schemas and apps (or protocol) won't require any update to use the new enhancements.
- `versioned` will mean that non-breaking change can't be made available until the schema is manually updated (which will then require doing some type of migration at the app level)

**Comment by nick-verida** [comment]
I think we should point to a version-numbered base schema.

Then if that base schema changes it's a deliberate choice to update the others to point to the new version and it gives devs the option to point to a fixed behaviour at a point in time.

**Comment by tahpot** [comment]
Yes, that sounds fair.

In the future, we can provide additional tools for developers to help them.

Add flexibility to `client-ts` so that a datastore can be opened with a given URL, but then specify the versions of other schema's they are prepared to include in the datastore when fetching data. For example:

```
const datastore = context.openDatastore("https://common.schemas.verida.io/social/contact/latest/schema.json", {
  "schemaVersions": [
    "v0.1.0",
    "v0.2.*"
  ]
})
```

**Comment by nick-verida** [comment]
@tahpot https://github.com/verida/schemas-core/ is now setup to autodeploy to S3. 

Currently the symlink isn't working. I'm looking into that now as well as setting up the other repos. But https://core.schemas.verida.io/schemas/base/v0.1.0/schema.json works. 

To make a deployment happen you just need to merge from `develop` to `main`.

In-progress documentation here: https://github.com/verida/infrastructure/tree/develop/schemas

**Comment by nick-verida** [comment]
Symlinks now work. 

https://core.schemas.verida.io/schemas/base/latest/schema.json

**Comment by nick-verida** [comment]
All three schema repos all deploy using the same mechanism. Slack notifications go the #devops-private channel. 

Documentation at https://github.com/verida/infrastructure/tree/develop/schemas

**Comment by tahpot** [comment]
Done:

- [x] Schemas have been split into core, vault and common
- [x] Schemas have been deployed
- [x] Issue created for @tahpot to update `verida-js`: https://github.com/verida/verida-js/issues/99
- [x] Issue created for @pkhien95 to update `vault-mobile`: https://github.com/verida/vault-mobile/issues/141
- [x] Issue created for @tahpot to enable developers to open schemas across multiple versions: https://github.com/verida/verida-js/issues/98
- [x] Issue created for @tahpot to add `draft-2020-12` schema validation support: https://github.com/verida/verida-js/issues/96

@nick-verida Can you create appropriate tasks to update the demos and docs as required and then close this issue?

**Comment by tahpot** [comment]
I've just realised there is one issue we will have with signatures.

If a piece of data has been signed by a third party and we perform a future migration of that data, we will change the `schema` property which in turn will break the signature.

Options:

1. Ignore the problem
1. Modify the signature scheme to not include any `schema` metadata in the signed data
1. Modify the signature scheme to retain the base `schema` URL, but drop all version information
1. Sign two versions of the data. 1) "as is", 2) with schema info dropped

I'm in favour of (3) as it seems semantically correct and ensures signatures don't unexpectedly break, however I'm concerned about that adding some complexity and potential confusion.

Data is versioned, so it would be possible to still recover the previously signed data with an older version and correct signature. On that basis (1) isn't awful.
